# This canary build pipeline is more than just publishing canaries
# This is where I playtest configurations before using it on our release pipeline
# So don't remove this unless you want to get a groundpound
# - Ayane Satomi 
name: Lint and Create Canary Build
on: push

jobs:
  lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Lint
         uses: github/super-linter@v3
         env:
           SUPPRESS_POSSUM: true
           LINTER_RULES_PATH: /
           VALIDATE_EDITORCONFIG: true
           EDITORCONFIG_FILE_NAME: .editorconfig
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
      name: Build and publish project
      needs: lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          runtime: [ win-x64, linux-x64 ]
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-dotnet@v1.7.2
          with:
             dotnet-version: '5.0.x'
             source-url: https://nuget.pkg.github.com/vignette-project/index.json
          env:
             NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

        - name: Build Project
          run: |
             dotnet publish Vignette.Desktop/Vignette.Desktop.csproj -c Release -o ./release/${{ matrix.runtime }} -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=false
             zip -r vignette-canary-${{ github.sha }}_${{ matrix.runtime }}.zip ./release/${{ matrix.runtime }}
        
        - name: Upload Canary build
          uses: actions/upload-artifact@master
          with:
            name: vignette-canary-${{ github.sha }}_${{ matrix.runtime }}
            path: vignette-canary-${{ github.sha }}_${{ matrix.runtime }}.zip