on: push
name: Lint
jobs:
  build:
    name: Lint Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          SUPPRESS_POSSUM: true
          LINTER_RULES_PATH: /
          VALIDATE_EDITORCONFIG: true
          EDITORCONFIG_FILE_NAME: .editorconfig
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}