on: push
name: Lint
jobs:
  build:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_XML: false
          VALIDATE_JSON: false
          VALIDATE_YAML: false
          VALIDATE_CSHARP: true
          VALIDATE_POWERSHELL: false
          VALIDATE_EDITORCONFIG: false