on: 
  release:
      types: [prereleased]
jobs:
  lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Lint
         uses: github/super-linter@v3
         env:
           SUPPRESS_POSSUM: true
           LINTER_RULES_PATH: /
           VALIDATE_EDITORCONFIG: true
           EDITORCONFIG_FILE_NAME: .editorconfig
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
  publish:
      name: Build and publish project
      needs: lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          runtime: [ win-x64, linux-x64 ]
      steps:
        - uses: actions/checkout@v2

        - name: Build Project
          run: |
             dotnet publish Vignette.Desktop/Vignette.Desktop.csproj -c Release -o ./release/${{ matrix.runtime }} -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
             zip -r vignette_insider-${{ github.ref }}_${{ matrix.runtime }}.zip ./release/${{ matrix.runtime }}
        
        - name: Generate Changelog
          uses: heinrichreimer/github-changelog-generator-action@v2.1.1
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             repo: vignette-project/vignette
             no-issues: true
             no-issues-wo-labels: true
             no-pr-wo-labels: true
             no-unreleased: true

        - name: Upload to VS App Center
          uses: wzieba/App-Center-action@v1.3.2
          with:
            appName: vignette/Vignette-AB1
            token: ${{ secrets.VS_APP_CENTER_TOKEN }}
            group: Insiders
            buildVersion: insider-${{ github.ref }}
            file: vignette_insider-${{ github.ref }}_${{ matrix.runtime }}.zip
            notifyTesters: true
            releaseNotes: CHANGELOG.md
       
        - name: Execute SSH Debug 
          uses: mxschmitt/action-tmate@master
          with:
            sudo: true
          if: ${{ failure() }}
          timeout-minutes: 120            
  notify:
     runs-on: ubuntu-latest
     needs: publish
     steps:
        - name: Notify Insiders
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_INS }}
          uses: Ilshidur/action-discord@master
          with:
            args: "Heads up <@&754332732716351618>! Vignette Build `vignette_insider-${{ github.ref }}` is now available! Visit the App Center to get your build."