on: 
  release:
      types: [released]
jobs:
  lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Lint
         uses: github/super-linter@v3
         env:
           SUPPRESS_POSSUM: true
           LINTER_RULES_PATH: /
           VALIDATE_EDITORCONFIG: true
           EDITORCONFIG_FILE_NAME: .editorconfig
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
  publish:
      name: Build and publish project
      needs: lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          runtime: [ win-x64, linux-x64 ]
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-dotnet@v1.7.2
          with:
             dotnet-version: '5.0.x'
             source-url: https://nuget.pkg.github.com/vignette-project/index.json
          env:
             NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

        - name: Build Project
          run: |
             dotnet publish Vignette.Desktop/Vignette.Desktop.csproj -c Release -o ./release/${{ matrix.runtime }} -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=false
             zip -r vignette-stable-${{ github.sha }}_${{ matrix.runtime }}.zip ./release/${{ matrix.runtime }}

        - name: Upload to VS App Center
          uses: wzieba/AppCenter-Github-Action@v1.3.2
          with:
            appName: vignette/Vignette-AB1
            token: ${{ secrets.VS_APP_CENTER_TOKEN }}
            group: Public
            buildVersion: stable-${{ github.sha }}
            file: vignette-stable-${{ github.sha }}_${{ matrix.runtime }}.zip
            notifyTesters: true           
  notify:
     runs-on: ubuntu-latest
     needs: publish
     steps:
        - name: Notify Public
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_REL }}
          uses: Ilshidur/action-discord@master
          with:
            args: "Heads up @everyone! Vignette Build `vignette-stable-${{ github.sha }}` is now available! Visit https://tinyurl.com/vignette-stable to get your build."
