name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Test
        run: dotnet test Vignette.Tests.sln --logger "trx;LogFileName=TestResults-Vignette.Tests.trx"

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Vignette.Tests
          path: ${{ github.workspace }}/Tests/Vignette.Tests/TestResults/TestResults-Vignette.Tests.trx